services:
  # api-gateway:
  #   build: ./api-gateway
  #   ports:
  #     - "3080:80"
  iot-db:
    build: ./iot-db
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - iot
  data-processor:
    extends:
      file: ./data-service/compose.yml
      service: app
    networks:
      - iot
    depends_on:
      - iot-db

networks:
  iot:
    driver: bridge
