services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3080:80"
  mqtt-server:
    build: ./mqtt-server
    ports:
      - "1884:1884"
    restart: unless-stopped
    networks:
      - iot
  iot-db:
    build: ./iot-db
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - iot
  auth-service:
    build: ./auth-service
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./auth-service/keys:/app/keys
    networks:
      - iot
  database:
    extends:
      file: ./database/docker-compose.yml
      service: db

networks:
  iot:
    driver: bridge

volumes:
  postgres_data:
