services:
  # api-gateway:
  #   build: ./api-gateway
  #   ports:
  #     - "3080:80"
  iot-db:
    build: ./iot-db
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - iot
  data-processor:
    extends:
      file: ./iot-service/compose.yml
      service: app
    restart: unless-stopped
    networks:
      - iot
      - prod
    depends_on:
      - iot-db
  backend:
    build: ./mobile-core
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - prod

  ml-service:
    build: ./ml-service
    restart: unless-stopped
    networks:
      - prod
      - iot
    depends_on:
      - iot-db
    env_file:
      - ./.env
networks:
  iot:
    driver: bridge
  prod:
    driver: bridge