
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017-27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8088:8088
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rootuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
      ME_CONFIG_MONGODB_URL: mongodb://rootuser:rootpass@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  mongo_data: